# This file is created automatically by `pak:::proj_create()`
# Please do not edit this file
dir.create('r-packages', showWarnings = FALSE, recursive = TRUE)
.libPaths(unique(c('r-packages', .libPaths())))
if (file.exists('~/.Rprofile')) source('~/.Rprofile')
